
name : appropriate_branch_master

on :
  pull_request_target :
    branches :
      - beta

jobs :

  appropriate_branch :
    uses : Wandalen/RustModuleCd/.github/workflows/AppropriateBranch.yml@master
    with :
      src_branch : 'alpha'
      dst_branch : '${{ github.base_ref }}'
    secrets :
      PRIVATE_GITHUB_BOT_TOKEN : '${{ secrets.PRIVATE_GITHUB_BOT_TOKEN }}'
