name : module1

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  # module1

  # test :
  #   uses : dmvict/CiCdTemplate/.github/workflows/StandardRustPush.yml@workflow
  #   with :
  #     manifest_path : 'module/module1/Cargo.toml'
  #     module_name : 'module1'
  #     commit_message : ${{ github.event.head_commit.message }}

  success :
    runs-on : ubuntu-latest
    steps :
      - run : exit 0
